[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "paypal.orders"
version = "2.0.1"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Payments", "Orders", "Vendor/Paypal", "Area/Finance", "Type/Connector"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-paypal.orders"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true
